language: objective-c
osx_image: xcode8.3
script:
- xcodebuild test -project CollapsibleTableSectionViewController.xcodeproj -scheme CollapsibleTableSectionViewController -destination 'platform=iOS Simulator,name=iPhone 7' | bundle exec xcpretty -c
